backend:
  name: github
  repo: deepanshuk2002/theindianfilmreporter.github.io
  branch: main

site_url: https://deepanshuk2002.github.io/theindianfilmreporter.github.io

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Content", name: "body", widget: "richtext" }
